### PR TITLE
Updated grid to allow user to send in unique ID field via rowMetadata

### PR DESCRIPTION
**Pull request by blkmutt**
This should provide consistent keys based on a column in the table to help with #104.

### CODE REVIEW

**Comment by blkmutt** [comment]
Changing the format of the rowMetadata.

**Comment by scvnc** [comment]
Maybe there is some way to DRY this code up so that the config-check logic isn't repeated between gridTable.js, griddle.js, among other places row _.uniqueId was previously being used.

Also, I think that this should produce a warning that _.uniqueId is being used if no key is defined in the rowMetadata config.

(edit: posting this here instead)

**Comment by joellanciaux** [comment]
Hrm, potentially moving this into `rowProperties.js` might make sense. 

Thanks a ton for putting this together @blkmutt :+1:

**Comment by blkmutt** [comment]
This is just doing the check one place, griddle.js is the built version. I think it would make more sense to put the config check in gridTable.js as we're checking to make sure the Row Properties exist. Mind you, I could put the check for the properties in gridTable.js and the check for the metadata in rowProperties.js ... thoughts?

**Comment by scvnc** [comment]
Ah, yeah :+1: having the build checked in to the repo is disorienting to me.

The two places I see for picking off `_.uniqueId` are gridTable.jsx and [gridRowContainer.jsx](https://github.com/BlackMuttMedia/Griddle/blob/master/scripts/gridRowContainer.jsx#L76). I assume it would be good to fix both of those.

**Comment by blkmutt** [comment]
Yeah, I believe we did pass it along. I did update rowProperties.js to include the check for the key, though, so it's at least clear in code. Also, let me know if you want the phrasing of the warning to be changed.

**Comment by joellanciaux** [comment]
It's already been said, but, yeah, it does need to happen on 'gridRowContainer' to when putting together rendering for subgrid rows.

Aside from it being in the two files, I think I'm a _little_ bit of an advocate for the check living in 'rowProperties', as it might allow the logic to be passed to customGrid/Row components.

**Comment by scvnc** [comment]
maybe like a `var key = that.props.rowSettings.getRowKey(row)` ? Return some configured key value or the result of `_.uniqueId`.  What do y'all think?

Also note the failing travis tests that may need to be updated.

**Comment by blkmutt** [comment]
I could update and put the row key logic right in there. Sounds good. Just as an FYI, if I do that, we'll have the warning for each row. Thoughts?

**Comment by scvnc** [comment]
As for warning for each row, in the grander scheme of things, I use a `WarnService` piece that wraps `console.warn` and can reduce multiple `warn()` calls to a single warn. It also handles silencing of warnings when webpack builds minified production code.

This is a package maintainer decision, but if it was up to me, I'd omit the warns for now and make a github issue to handle this more robustly later.  The docs have to be updated too.

**Comment by blkmutt** [comment]
Alright, logic should be in rowProperties.js and documentation should be updated.

**Comment by joellanciaux** [comment]
:+1: Sweet deal.  Thanks again @blkmutt!

@scvnc Regarding wrapping up warnings in a service, that would be slick, but it might negate a little bit of the usefulness of the 'no row key' error in general use. It's definitely worth discussing, though.

**Comment by ohana54** [comment]
@blkmutt Thanks for the fix! One question though, why internally are you using an array as a default value when the api expects an object? Did I miss something?

**Comment by blkmutt** [comment]
No, you didn't ... I did. I'd initially had it set up like the Column Properties, but realized it just didn't make sense. I'll try to make some updates and get a fix out today.

**Comment by joellanciaux** [comment]
@blkmutt @ohana54 I believe that I updated that while I was pulling it in to `master`. Did I possibly miss something? https://github.com/DynamicTyped/Griddle/blob/master/scripts/rowProperties.js

**Comment by blkmutt** [comment]
Yeah, it actually looks like you did, @joellanciaux.

**Comment by weitenghuang** [comment]
do you have an example how to assign unique key when using `rowMetadata` props?

**Comment by weitenghuang** [comment]
When I try to have isomorphic griddle-react, i realize i will need to provide `rowMetadata={{"key":columnName}}`, otherwise _.uniqueId() seems to cause the react invalid checkSum issue between server and client rendering. Maybe we can add this to griddle's document?

**Pull request merged**
